version: '3.4'

services:
  webapp.server:
    image: ${DOCKER_REGISTRY-}webappserver
    build:
      context: .
      dockerfile: WebApplication1/Server/Dockerfile
    # environment:
    #   - ASPNETCORE_URLS=http://*:80
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1#
